# This is a basic workflow to help you get started with Actions

name: Paint Contribution Map

# Run function every day at 2am UTC everyday
on:
  schedule:
  - cron: "0 2 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      # Commands to run each time
      - name: Conditionally make a change to log.txt
        run: |
          echo "Checking if a commit is needed today"

          # read in space invaders pattern
          PATTERN=$(head -n 1 pattern.txt)
          echo $PATTERN

          # calculate days since May 15 2022
          MAY_15_2022=1652572800
          RUN_TIME=$(date +%s)
          SECONDS_ELAPSED=$((RUN_TIME - MAY_15_2022))
          DAYS_ELAPSED=$((SECONDS_ELAPSED / (60 * 60 * 24)))

          # test case
          # DAYS_ELAPSED=1

          # calculate the offset, correcting overflow
          OFFSET=$(( $DAYS_ELAPSED  % 364 ))
          echo "The offset is $OFFSET days"

          # map the offset to the value in the pattern
          PATTERN_VALUE=${PATTERN:OFFSET:1}

          # conditionally write to a text file
          if ((PATTERN_VALUE == 0)); then
             echo "The pattern value is 0"        
          fi

          if ((PATTERN_VALUE == 1)); then
             echo "The pattern value is 1, so a commit will be made"   
             printf $"Made a commit at: $(date)\n" >> log.txt     
          fi
          
      # make commit if log.txt was changed
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated commit
